- type: job
  id: MedicalDoctor
  name: "medical doctor"
  startingGear: DoctorGear
  departments:
  - Medical
  icon: "MedicalDoctor"
  supervisors: "the chief medical officer"
  access:
    - Captain
    - HeadOfPersonnel
    - ChiefEngineer
    - ChiefMedicalOfficer
    - HeadOfSecurity
    - ResearchDirector
    - Command
    - Security
    - Armory
    - Engineering
    - Medical
    - Cargo
    - Research
    - Service
    - Maintenance
    - External
    - Janitor
    - Theatre
    - Bar
    - Chemistry
    - Kitchen
    - Chapel
    - Hydroponics

- type: startingGear
  id: DoctorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    outerclothing: ClothingOuterCoatLab
    id: MedicalPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpskirtMedicalDoctor
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
