- type: job
  id: CentralCommandOffical
  name: "centcom official"
  setPreference: false
  startingGear: CentcomGear
  departments:
    - Command
  icon: "Nanotrasen"
  supervisors: "the head of security"
  access:
    - Captain
    - HeadOfPersonnel
    - ChiefEngineer
    - ChiefMedicalOfficer
    - HeadOfSecurity
    - ResearchDirector
    - Command
    - Security
    - Armory
    - Engineering
    - Medical
    - Cargo
    - Research
    - Service
    - Maintenance
    - External
    - Janitor
    - Theatre
    - Bar
    - Chemistry
    - Kitchen
    - Chapel
    - Hydroponics

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerclothing: ClothingOuterVestKevlar
    id: CentcomPDA
    ears: ClothingHeadsetAltCommand
    pocket1: Paper
    pocket2: Pen
