- type: job
  id: HeadOfPersonnel
  name: "head of personnel"
  startingGear: HoPGear
  departments:
  - Command
  - Civilian
  icon: "HeadOfPersonnel"
  requireAdminNotify: true
  supervisors: "the captain"
  canBeAntag: false
  access:
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Command
  - Security
  - Armory
  - Engineering
  - Medical
  - Cargo
  - Research
  - Service
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics

- type: startingGear
  id: HoPGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatHopcap
    id: HoPPDA
    ears: ClothingHeadsetAltCommand
  innerclothingskirt: ClothingUniformJumpskirtHoP
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
