- type: job
  id: Warden
  name: "warden"
  startingGear: WardenGear
  departments:
  - Security
  icon: "Warden"
  supervisors: "the head of security"
  canBeAntag: false
  access:
    - Captain
    - HeadOfPersonnel
    - ChiefEngineer
    - ChiefMedicalOfficer
    - HeadOfSecurity
    - ResearchDirector
    - Command
    - Security
    - Armory
    - Engineering
    - Medical
    - Cargo
    - Research
    - Service
    - Maintenance
    - External
    - Janitor
    - Theatre
    - Bar
    - Chemistry
    - Kitchen
    - Chapel
    - Hydroponics

- type: startingGear
  id: WardenGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterCoatWarden
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
