- type: job
  id: ChiefEngineer
  name: job-name-ce
  weight: 10
  startingGear: ChiefEngineerGear
  departments:
  - Command
  - Engineering
  icon: "ChiefEngineer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  accessGroups:
    - AllAccess

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    head: ClothingHeadHatHardhatWhite
    jumpsuit: ClothingUniformJumpsuitChiefEngineer
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesColorBrown
    id: CEPDA
    ears: ClothingHeadsetCE
    belt: ClothingBeltChiefEngineerFilled
  innerclothingskirt: ClothingUniformJumpskirtChiefEngineer
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
