- type: job
  id: StationEngineer
  name: job-name-engineer
  startingGear: StationEngineerGear
  departments:
  - Engineering
  icon: "StationEngineer"
  supervisors: job-supervisors-ce
  accessGroups:
    - AllAccess

- type: startingGear
  id: StationEngineerGear
  equipment:
    head: ClothingHeadHatHardhatYellow
    jumpsuit: ClothingUniformJumpsuitEngineering
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterVestHazard
    id: EngineerPDA
    belt: ClothingBeltUtilityFilled
    ears: ClothingHeadsetEngineering
  innerclothingskirt: ClothingUniformJumpskirtEngineering
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
