- type: job
  id: Assistant
  name: "assistant"
  startingGear: AssistantGear
  departments:
  - Civilian
  icon: "Assistant"
  supervisors: "absolutely everyone"
  accessGroups:
    - AllAccess

- type: startingGear
  id: AssistantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: AssistantPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtColorGrey
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: job
  id: Vagabond
  name: "vagabond"
  startingGear: AssistantGear
  departments:
    - Civilian
  icon: "Assistant"
  supervisors: "absolutely nobody"
  access:
    - Captain
    - HeadOfPersonnel
    - ChiefEngineer
    - ChiefMedicalOfficer
    - HeadOfSecurity
    - ResearchDirector
    - Command
    - Security
    - Armory
    - Engineering
    - Medical
    - Cargo
    - Research
    - Service
    - Maintenance
    - External
    - Janitor
    - Theatre
    - Bar
    - Chemistry
    - Kitchen
    - Chapel
    - Hydroponics
