- type: job
  id: Chef
  name: job-name-chef
  startingGear: ChefGear
  departments:
  - Civilian
  icon: "Chef"
  supervisors: job-supervisors-hop
  accessGroups:
    - AllAccess

- type: startingGear
  id: ChefGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChef
    head: ClothingHeadHatChef
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: ChefPDA
    ears: ClothingHeadsetService
    outerClothing: ClothingOuterApronChef
  innerclothingskirt: ClothingUniformJumpskirtChef
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
