- type: job
  id: Clown
  name: "clown"
  startingGear: ClownGear
  departments:
  - Civilian
  icon: "Clown"
  supervisors: "the head of personnel"
  access:
    - Captain
    - HeadOfPersonnel
    - ChiefEngineer
    - ChiefMedicalOfficer
    - HeadOfSecurity
    - ResearchDirector
    - Command
    - Security
    - Armory
    - Engineering
    - Medical
    - Cargo
    - Research
    - Service
    - Maintenance
    - External
    - Janitor
    - Theatre
    - Bar
    - Chemistry
    - Kitchen
    - Chapel
    - Hydroponics
  special:
  - !type:AddComponentSpecial
    component: Clumsy # Adds ClumsyComponent to the mob.

- type: startingGear
  id: ClownGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitClown
    back: ClothingBackpackClownFilled
    shoes: ClothingShoesClown
    mask: ClothingMaskClown
    pocket1: BikeHorn
    id: ClownPDA
    ears: ClothingHeadsetService
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelClownFilled
