- type: job
  id: Librarian
  name: job-name-librarian
  startingGear: LibrarianGear
  departments:
  - Civilian
  icon: "Librarian"
  supervisors: job-supervisors-hop
  accessGroups:
    - AllAccess

- type: startingGear
  id: LibrarianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLibrarian
    back: ClothingBackpackBriefcaseFilled
    shoes: ClothingShoesColorBlack
    id: LibrarianPDA
    ears: ClothingHeadsetService
    pocket1: d10Dice
  innerclothingskirt: ClothingUniformJumpskirtColorLightBrown

