- type: job
  id: ResearchDirector
  name: "research director"
  head: true
  startingGear: ResearchDirectorGear
  departments:
  - Command
  - Science
  icon: "ResearchDirector"
  requireAdminNotify: true
  supervisors: "the captain"
  canBeAntag: false
  accessGroups:
    - AllAccess

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatLab
    id: RnDPDA
    ears: ClothingHeadsetScience
  innerclothingskirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
