- type: job
  id: ResearchDirector
  name: job-name-rd
  weight: 10
  startingGear: ResearchDirectorGear
  departments:
  - Command
  - Science
  icon: "ResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  accessGroups:
    - AllAccess

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatLab
    id: RnDPDA
    ears: ClothingHeadsetRD
  innerclothingskirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
